runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /
    script: handlers.index.app

  - url: /templates
    static_dir: templates
    application_readable: true

  - url: /trips/.*
    script: handlers.trips.app
    login: required

  - url: /error/.*
    script: handlers.error.app
    login: required


libraries:
  - name: webapp2
    version: "2.5.2"
  - name: jinja2
    version: latest
