runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /
    script: handlers.index.app

  - url: /templates
    static_dir: templates
    application_readable: true

  - url: /resources
    static_dir: resources

  - url: /trips/manage
    script: handlers.trips.manage.app
    login: required

  - url: /trips/add
    script: handlers.trips.add.app
    login: required

libraries:
  - name: webapp2
    version: "2.5.2"
  - name: jinja2
    version: latest
